### PR TITLE
Apply some opinionated code formatting

### PR DESCRIPTION
**Pull request by eXpl0it3r**
This is more my personal preference on how to format code. Feel free to close the PR if you prefer the existing format. 🙂 

- Spaces after keywords like if, catch, while, for, etc.
- Space before the opening body brace
- One line comments (`//`) should start with a space

### CODE REVIEW

**Comment by elijahfhopp** [comment]
I am thinking of merging this. I think it is a great change of the ReadMe, but I am not sure if I want to change the existing codebase because then my OCD would kick in and I would write all RLL's code with this style. :smile: 

Do you mind if I make these changes to the ReadMe outside of the PR?

**Comment by eXpl0it3r** [comment]
The PR should already cover the whole RLL code base. 😉 
But I don't mind if you just take part of it or none of it. You can also edit this PR btw.

**Comment by elijahfhopp** [comment]
Ah, sorry. My phrasing was confusing. I meant that any additions to RLL I wrote would have to keep the same style because of my needless scrupulosity, :P.

I will edit the PR and merge it now.

**Review by elijahfhopp — APPROVED** [review]

**Comment by elijahfhopp** [comment]
Thanks!

**Pull request merged**
